<?php

return [
    'navigation' => [
        'getting_started' => [
            'title' => 'Getting Started',
            'pages' => [
                'introduction' => 'Introduction',
                'installation' => 'Installation',
                'theming' => 'Theming',
                'components' => 'Components',
            ],
        ],
        'components' => [
            'title' => 'Components',
            'library' => [
                'Accordion' => ['description' => 'A vertically stacked set of interactive headings', 'category' => 'Layout'],
                'Alert' => ['description' => 'Displays a callout for user attention', 'category' => 'Feedback'],
                'Avatar' => ['description' => 'An image element with a fallback for representing the user', 'category' => 'Data Display'],
                'Badge' => ['description' => 'Small status descriptors for UI elements', 'category' => 'Data Display'],
                'Breadcrumbs' => ['description' => 'Shows the navigation path to the current page', 'category' => 'Navigation'],
                'Button' => ['description' => 'Interactive buttons with multiple variants', 'category' => 'Form'],
                'Carousel' => ['description' => 'A slideshow component for cycling through elements', 'category' => 'Layout'],
                'Command Palette' => ['description' => 'Fast, accessible command interface', 'category' => 'Navigation'],
                'Data Table' => ['description' => 'Powerful table component with sorting and filtering', 'category' => 'Data Display'],
                'Date Picker' => ['description' => 'Calendar component for date selection', 'category' => 'Form'],
                'Drawer' => ['description' => 'A panel that slides in from the edge of the screen', 'category' => 'Layout'],
                'Dropdown' => ['description' => 'A list of options that appears when triggered', 'category' => 'Navigation'],
                'Empty State' => ['description' => 'Display content when no data is available', 'category' => 'Layout'],
                'File Upload' => ['description' => 'File input with drag and drop support', 'category' => 'Form'],
                'Input' => ['description' => 'Form inputs with validation states', 'category' => 'Form'],
                'Kbd' => ['description' => 'Displays keyboard shortcuts and keys', 'category' => 'Data Display'],
                'Modal' => ['description' => 'Dialog that appears on top of the page content', 'category' => 'Layout'],
                'Popover' => ['description' => 'Non-modal dialog that floats around a trigger', 'category' => 'Navigation'],
                'Progress Bar' => ['description' => 'Shows the completion status of a task', 'category' => 'Feedback'],
                'Progress Steps' => ['description' => 'Visual indicator of step completion', 'category' => 'Feedback'],
                'Range Slider' => ['description' => 'Input for selecting a value from a range', 'category' => 'Form'],
                'Rating' => ['description' => 'Star rating input component', 'category' => 'Form'],
                'Skeleton' => ['description' => 'Placeholder content while loading', 'category' => 'Feedback'],
                'Sortable List' => ['description' => 'Draggable list with sorting capabilities', 'category' => 'Data Display'],
                'Stat Card' => ['description' => 'Display statistics and metrics', 'category' => 'Data Display'],
                'Stepper' => ['description' => 'Input for incrementing or decrementing values', 'category' => 'Form'],
                'Tabs' => ['description' => 'Organize content into separate views', 'category' => 'Layout'],
                'Timeline' => ['description' => 'Display a list of events in chronological order', 'category' => 'Data Display'],
                'Toast' => ['description' => 'Non-intrusive notifications', 'category' => 'Feedback'],
                'Toggle' => ['description' => 'A two-state button that can be either on or off', 'category' => 'Form'],
                'Tooltip' => ['description' => 'Provides additional information on hover', 'category' => 'Feedback'],
            ],
        ],
    ],
];
